/**
 * The docs collection.
 *
 * The markdown in `src/content/docs/` is generated by `scripts/sync-docs.mjs`
 * and gitignored, so this schema is a contract between two things that never
 * meet: the sync script writes it, the pages read it. `group` and `order` are
 * copied from `src/docs/nav.mjs`, which the sidebar, prev/next and the index
 * read as well — so a page cannot be listed in the nav and out of order at the
 * same time.
 */
import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
// Astro's own copy of zod: importing `z` from 'astro:content' still works but
// is deprecated, and `astro check` says so.
import { z } from 'astro/zod';

const docs = defineCollection({
	loader: glob({ pattern: '**/*.md', base: './src/content/docs' }),
	schema: z.object({
		/** The nav title, which is also the page's H1. */
		title: z.string(),
		/** One sentence, used for the lede, the meta description and the cards. */
		description: z.string(),
		group: z.string(),
		order: z.number(),
		/** Where it came from in the app repo, printed in the page footer. */
		source: z.string()
	})
});

export const collections = { docs };
